version: "3.7"

services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/traefik.yml:ro"
    networks:
      - default
      - kiosk-int
    labels:
      - "traefik.docker.network=kiosk-int"

# Для тестирования роутов traefik
  # nginx:
  #   image: nginx:1.16.0-alpine
  #   networks:
  #     - kiosk-int
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.nginx.entrypoints=web"
  #     - "traefik.http.services.nginx.loadbalancer.server.port=80"
  #     #- "traefik.http.routers.nginx.rule=Host(`nginx.$MY_DOMAIN`)"
  #     - "traefik.docker.network=kiosk-int"
  #     - "traefik.http.routers.nginx.rule=Path(`/foo`)"



networks:
  kiosk-int:
    internal: true

  default:
    external:
      name: kiosk-net

